version: '3.9'
services:
  database-kuma:
    image: postgres:15
    container_name: database-kuma
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
      
  server:
    build: ./server
    container_name: server
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: database
      POSTGRES_PORT: 5431
      POSTGRES_AUTO_MIGRATE: true
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BACKEND_PORT: 8080
      MODE: release
    ports:
      - "8081:8080"
    depends_on:
      - database-kuma
    volumes:
      - ./volumes/backend:/app